name: ag_viewer
description: UnOfficial A&G+ App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1

  firebase_core:
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.1+3
  firebase_analytics:
  firebase_remote_config:
  firebase_messaging:

  flutter_riverpod:
  rxdart:
  equatable:

  enum_to_string:
  package_info:
  pub_semver:
  url_launcher:
  fluttertoast:
  video_player:
    git:
      url: git@github.com:YuheiNakasaka/flutter-plugins.git
      ref: fix/ios-hls-bug
      path: packages/video_player/video_player
  flutter_inappwebview: ^4.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  pedantic_mono:

flutter:
  uses-material-design: true