name: ag_viewer
description: UnOfficial A&G+ App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:

  firebase_core:
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.1+3
  firebase_analytics:
  firebase_remote_config:
  firebase_messaging:

  flutter_riverpod:
  rxdart:
  equatable:

  enum_to_string:
  package_info:
  device_info:
  app_settings:
  pub_semver:
  url_launcher:
  fluttertoast:
  flutter_inappwebview: ^4.0.0+4
  video_player:
    path: ../flutter-plugins/packages/video_player/video_player

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  pedantic_mono:
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - assets/hls.html

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"